# Generated by Django 4.2.6 on 2023-10-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_categeroies'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.categeroies'),
            preserve_default=False,
        ),
    ]
