# Generated by Django 4.2.6 on 2023-11-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_hotelbooking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
