# Generated by Django 4.2.6 on 2023-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_hotel_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Ammount',
            field=models.IntegerField(max_length=5),
        ),
    ]
