# Generated by Django 4.2.6 on 2023-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_hotel_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='Ammount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
