# Generated by Django 4.2.6 on 2023-11-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_hotelbooking_ammount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='Ammount',
        ),
    ]
