# Generated by Django 4.2.6 on 2023-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_remove_hotelbooking_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('NET_BANKING', 'Net Banking')], max_length=20),
        ),
    ]
